### ISSUE TITLE
FILE *stdout causes errors on cygwin, gcc 5.4.0

### ISSUE THREAD

**Issue by JungHong** [jhunt/ctap#9]
In ctap.h, the line FILE *stdout causes errors on cygwin, gcc 5.4.0.

When the line is changed to FILE *ctap_stdout and all use of .stdout is changed to .ctap_stdout,
then all tests compile and execute without errors.

**Comment by jhunt** [comment]
This line?

https://github.com/jhunt/ctap/blob/master/include/ctap.h#L125

Can you provide the actual error output?

**Comment by JungHong** [comment]
Thanks for replying.
Yes.  I will change the source back to as-distributed, capture the actual error message, and post.

**Comment by JungHong** [comment]
Per your request:  the distribution ctap.h was copied to cap.h
make check >& actual_error.txt 
The file actual_error.txt is attached.

When I make the changes suggested in a prior post, 'make check' completes without errors.


[actual_error.txt](https://github.com/jhunt/ctap/files/887783/actual_error.txt)

**Comment by jhunt** [comment]
Do you mind posting the output of `gcc -E include/ctap.h`?
